name: xsref tests

on: [ push, pull_request ]

jobs:
  xsref_tests:
    name: xsref table consistency tests
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: prefix-dev/setup-pixi@92815284c57faa15cd896c4d5cfb2d59f32dc43d # v0.8.3
        with:
          pixi-version: v0.76.1
          cache: true
          environments: tests

      - name: Run tests
        run: pixi run tests

  pixi_packages:
    name: Build Pixi packages
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set caches to D drive (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          'UV_CACHE_DIR=D:\uv_cache' >> $env:GITHUB_ENV
          'RATTLER_CACHE_DIR=D:\rattler_cache' >> $env:GITHUB_ENV

      - uses: prefix-dev/setup-pixi@92815284c57faa15cd896c4d5cfb2d59f32dc43d # v0.8.3
        with:
          pixi-version: v0.76.1
          run-install: false

      - name: Publish Pixi package
        run: pixi publish
